// Build a single executable: `npm run build:sea`.
//
// Node's SEA (Single Executable Application) takes ONE CommonJS file and
// injects it into a copy of the node binary. This app is neither one file nor
// CommonJS, so the build does three things before it gets there:
//
//   1. writes src/commands/_manifest.cjs — a static list of every command, so
//      the loader doesn't have to read a directory that won't exist inside an
//      executable (the loader falls back to the directory scan without it, so
//      a normal install is unaffected)
//   2. inlines views/, public/ and the persona template as base64 in a
//      generated entry file; at startup they are written into the data
//      directory and the app is pointed at that copy
//   3. bundles the whole thing with esbuild into one CommonJS file, then runs
//      the standard `node --experimental-sea-config` + postject dance
//
// What it does NOT solve: ffmpeg. `ffmpeg-static` ships an 80 MB platform
// binary that has to exist on disk to be executed, so the executable looks for
// ffmpeg on PATH (or at the path set in Settings → Media) and falls back to
// raw-JPEG previews without it. Everything else works.
//
// Requires esbuild and postject, both used only here:
//   npm i -D esbuild postject

import { execFileSync } from "node:child_process";
import * as esbuild from "esbuild";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const BUILD = path.join(ROOT, "build");
const OUT_NAME = process.platform === "win32" ? "levix.exe" : "levix";

const step = (message) => console.log(`\n▸ ${message}`);
const rel = (file) => path.relative(ROOT, file);

fs.rmSync(BUILD, { recursive: true, force: true });
fs.mkdirSync(BUILD, { recursive: true });

// ---------------------------------------------------------------------------
// 1. The command manifest
// ---------------------------------------------------------------------------

step("Writing the command manifest");

function commandFiles() {
  const base = path.join(ROOT, "src", "commands");
  const entries = [];

  for (const entry of fs.readdirSync(base, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      for (const file of fs.readdirSync(path.join(base, entry.name))) {
        if (file.endsWith(".cjs")) {
          entries.push({ spec: `./${entry.name}/${file}`, category: entry.name });
        }
      }
    } else if (entry.name.endsWith(".cjs") && !entry.name.startsWith("_")) {
      entries.push({ spec: `./${entry.name}`, category: null });
    }
  }
  return entries.sort((a, b) => a.spec.localeCompare(b.spec));
}

function writeManifest(file, entries) {
  fs.writeFileSync(
    file,
    [
      "// GENERATED by scripts/build-sea.mjs — do not edit, and do not commit.",
      "//",
      "// A packaged executable has no directory to read, so the loader takes",
      "// this list instead. Delete it and the loader goes back to scanning.",
      "",
      "module.exports = [",
      ...entries.map(
        ({ spec, category }) =>
          `  { label: ${JSON.stringify(spec)}, category: ${JSON.stringify(
            category
          )}, module: require(${JSON.stringify(spec)}) },`
      ),
      "];",
      "",
    ].join("\n")
  );
}

const commands = commandFiles();
const manifestPath = path.join(ROOT, "src", "commands", "_manifest.cjs");
// `group` loads its own sub-commands the same way, one directory down.
const groupManifestPath = path.join(ROOT, "src", "commands", "group", "_manifest.cjs");
const manifestPaths = [manifestPath, groupManifestPath];

writeManifest(manifestPath, commands);
writeManifest(
  groupManifestPath,
  commands
    .filter((entry) => entry.category === "group")
    .map((entry) => ({ spec: `./${path.basename(entry.spec)}`, category: "group" }))
);
console.log(`  ${commands.length} commands -> ${rel(manifestPath)}`);

// ---------------------------------------------------------------------------
// 2. Assets + the entry file
// ---------------------------------------------------------------------------

step("Inlining views, public and the persona template");

function collect(dir, prefix, into) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    const name = `${prefix}/${entry.name}`;
    if (entry.isDirectory()) collect(full, name, into);
    else into[name] = fs.readFileSync(full).toString("base64");
  }
}

const assets = {};
collect(path.join(ROOT, "views"), "views", assets);
collect(path.join(ROOT, "public"), "public", assets);
assets["src/config/ai-persona.md"] = fs
  .readFileSync(path.join(ROOT, "src", "config", "ai-persona.md"))
  .toString("base64");

const assetBytes = Object.values(assets).reduce(
  (total, base64) => total + Math.floor((base64.length * 3) / 4),
  0
);
console.log(
  `  ${Object.keys(assets).length} files, ${(assetBytes / 1024).toFixed(0)} KB`
);

const assetsFile = path.join(BUILD, "assets.generated.cjs");
fs.writeFileSync(
  assetsFile,
  `module.exports = ${JSON.stringify(assets)};\n`
);

// CommonJS on purpose: `require` here has to be the bundler's, not one made
// with createRequire — the latter would be resolved on disk at runtime, which
// is exactly what an executable can't do.
const entryFile = path.join(BUILD, "entry.cjs");
fs.writeFileSync(
  entryFile,
  `// GENERATED by scripts/build-sea.mjs.
//
// The executable's first job is to put the files the app expects to read from
// disk (templates, stylesheets, images) somewhere the filesystem can see, then
// point the app at that copy. After that it is the ordinary bot.

const fs = require("node:fs");
const path = require("node:path");

const assets = require("./assets.generated.cjs");
const paths = require("../src/config/paths.cjs");

const stamp = ${JSON.stringify(String(Date.now()))};
const root = paths.dataPath("assets", stamp);

if (!fs.existsSync(root)) {
  for (const [name, base64] of Object.entries(assets)) {
    const target = path.join(root, name);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, Buffer.from(base64, "base64"));
  }
  // An older build left its own copy behind; this one is in use, drop the rest.
  const parent = paths.dataPath("assets");
  for (const entry of fs.readdirSync(parent)) {
    if (entry !== stamp) {
      fs.rmSync(path.join(parent, entry), { recursive: true, force: true });
    }
  }
}

paths.setAssetRoot(root);

// The CLI, not the bot: the executable supports every subcommand
// (headless, where, reset-password, domain) exactly like \`levix\` does.
require("../src/cli.js").run(process.argv);
`
);

// ---------------------------------------------------------------------------
// 3. Bundle, then inject
// ---------------------------------------------------------------------------

const bundleFile = path.join(BUILD, "levix.bundle.cjs");

step("Bundling with esbuild");

// Fifteen ESM files do `const require = createRequire(import.meta.url)` and
// then require a .cjs sibling. esbuild inlines a plain `require("./x.cjs")`
// but not one made through createRequire, so those modules would be looked up
// on disk at runtime — inside an executable that has no disk to look at.
// Dropping the createRequire line turns them into plain requires, which the
// bundler then resolves like any other import.
// ffmpeg-static resolves a path to a native binary that lives in
// node_modules. There is no node_modules in an executable, and leaving it
// external makes the require throw at startup — so it resolves to null here
// and the thumbnail code falls through to `ffmpeg` on PATH (or whatever
// Settings -> Media points at).
const stubFfmpegStatic = {
  name: "stub-ffmpeg-static",
  setup(build) {
    build.onResolve({ filter: /^ffmpeg-static$/ }, () => ({
      path: "ffmpeg-static",
      namespace: "levix-stub",
    }));
    build.onLoad({ filter: /.*/, namespace: "levix-stub" }, () => ({
      contents: "module.exports = null;",
      loader: "js",
    }));
  },
};

const unwrapCreateRequire = {
  name: "unwrap-create-require",
  setup(build) {
    build.onLoad({ filter: /src[\\/].*\.js$/ }, async (args) => {
      const source = await fs.promises.readFile(args.path, "utf8");
      if (!source.includes("createRequire(import.meta.url)")) return null;
      return {
        contents: source.replace(
          /^const require = createRequire\(import\.meta\.url\);$/m,
          "// createRequire removed by the SEA build — see scripts/build-sea.mjs"
        ),
        loader: "js",
      };
    });
  },
};

await esbuild.build({
  entryPoints: [entryFile],
  bundle: true,
  platform: "node",
  target: "node24",
  format: "cjs",
  outfile: bundleFile,
  plugins: [unwrapCreateRequire, stubFfmpegStatic],
  // Whatever is left of import.meta after the plugin (a __dirname derivation
  // or two) points at the bundle itself.
  define: { "import.meta.url": "__levixBundleUrl" },
  banner: {
    js: "const __levixBundleUrl = require('node:url').pathToFileURL(__filename).href;",
  },
  logLevel: "warning",
  logLimit: 0,
});
console.log(
  `  ${(fs.statSync(bundleFile).size / 1024 / 1024).toFixed(1)} MB -> ${rel(bundleFile)}`
);

step("Preparing the SEA blob");
const seaConfig = path.join(BUILD, "sea-config.json");
fs.writeFileSync(
  seaConfig,
  JSON.stringify(
    {
      main: bundleFile,
      output: path.join(BUILD, "sea-prep.blob"),
      disableExperimentalSEAWarning: true,
      useSnapshot: false,
      useCodeCache: false,
    },
    null,
    2
  )
);
execFileSync(process.execPath, ["--experimental-sea-config", seaConfig], {
  stdio: "inherit",
  cwd: ROOT,
});

step("Copying the node binary");
const outFile = path.join(BUILD, OUT_NAME);
fs.copyFileSync(process.execPath, outFile);
fs.chmodSync(outFile, 0o755);

if (process.platform === "darwin") {
  // macOS refuses to run a binary whose signature no longer matches its
  // contents; strip it now and re-sign ad-hoc after the injection.
  try {
    execFileSync("codesign", ["--remove-signature", outFile], { stdio: "inherit" });
  } catch {
    console.log("  (codesign not available — you may have to sign it yourself)");
  }
}

step("Injecting");
execFileSync(
  process.execPath,
  [
    path.join(ROOT, "node_modules", "postject", "dist", "cli.js"),
    outFile,
    "NODE_SEA_BLOB",
    path.join(BUILD, "sea-prep.blob"),
    "--sentinel-fuse",
    "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2",
    ...(process.platform === "darwin"
      ? ["--macho-segment-name", "NODE_SEA"]
      : []),
  ],
  { stdio: "inherit", cwd: ROOT }
);

if (process.platform === "darwin") {
  try {
    execFileSync("codesign", ["--sign", "-", outFile], { stdio: "inherit" });
  } catch {}
}

for (const file of manifestPaths) fs.rmSync(file, { force: true });

const size = (fs.statSync(outFile).size / 1024 / 1024).toFixed(0);
console.log(
  [
    "",
    `  Built ${rel(outFile)} (${size} MB) for ${process.platform}-${os.arch()}.`,
    "",
    "  It carries its own Node, its own SQLite and its own control panel.",
    "  It does NOT carry ffmpeg: install it (or set the path in Settings) if",
    "  you want video thumbnails.",
    "",
    "  One binary per platform — build it on the machine you are targeting.",
    "",
  ].join("\n")
);
